proxies:
proxy-groups:
  - name: Servers
    type: select
    proxies:
      - Universal
      - SG LB
      - ID LB
  - name: Universal
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 300
    use:
      - "1. Main Server"
  - name: SG LB
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 300
    use:
      - "2. Group SG"
  - name: ID LB
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 300
    use:
      - "3. Group ID"
proxy-providers:
  "1. Main Server":
    type: http
    url: "https://raw.githubusercontent.com/DummyAccount8431/ContohCFM/main/proxy_provider/main_server.yaml"
    interval: 3600
    path: ./proxy_provider/main_server.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  "2. Group SG":
    type: http
    url: "https://raw.githubusercontent.com/DummyAccount8431/ContohCFM/main/proxy_provider/group_sg.yaml"
    interval: 3600
    path: ./proxy_provider/group_sg.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  "3. Group ID":
    type: http
    url: "https://raw.githubusercontent.com/DummyAccount8431/ContohCFM/main/proxy_provider/group_id.yaml"
    interval: 3600
    path: ./proxy_provider/group_id.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
rules:
  - IP-CIDR,127.0.0.1/32,REJECT,no-resolve
  - IP-CIDR6,::1/128,REJECT,no-resolve
  - MATCH,Servers
  
